const plasticConsequencesContent = "Schade aan de Dierenwereld - Plastic dat in de oceaan terechtkomt, is heel slecht voor de dieren en planten die daar leven. Als dieren, zoals schildpadden, zeevogels, vissen, plastic tegenkomen of inslikken, kunnen ze er erg ziek van worden of zelfs doodgaan. Sommige dieren raken verstrikt in plastic en kunnen niet meer bewegen." +
    
"Zelfs dieren op het land kunnen in de problemen komen door plastic. Grote dieren zoals olifanten, hyena's, zebra's en tijgers hebben soms plastic ingeslikt, wat heel gevaarlijk kan zijn. Het kan ervoor zorgen dat ze ziek worden of zelfs doodgaan. Ook heeft onderzoek aangetoond dat plastic schade kan veroorzaken aan de lever en cellen van dieren. Het kan ervoor zorgen dat sommige dieren minder eieren leggen, zoals oesters." +

"Maar er zijn nog meer problemen met plastic. Plastic voorwerpen die in het water drijven, kunnen ook zorgen dat andere dieren op plekken komen waar ze niet thuishoren. Dit kan gevaarlijk zijn voor de plek waar de dieren leven en voor het eten dat ze nodig hebben." + 

"Gezondheidsrisico's - Microplastics kunnen zich ophopen in de voedselketen en uiteindelijk ook in ons voedsel terechtkomen. Dit kan gevaarlijk zijn voor onze gezondheid. Plastic kan ziekte veroorzaken en problemen geven met onze groei, ons denken, onze voortplanting en ons afweersysteem. Ook kunnen er giftige stoffen op het plastic zitten die naar ons toe komen als we vis eten die in plastic vervuild water heeft gezwommen." + 

"Economische schade - De plasticvervuiling in de oceanen heeft negatieve gevolgen voor de visserij, het toerisme en andere industrieën die afhankelijk zijn van gezonde oceanen. Volgens onderzoek kosten de problemen met plastic in de oceaan elk jaar tussen de $6 en $19 miljard dollar. Deze kosten worden veroorzaakt door de impact op toerisme, visserij en schoonmaakacties die de overheid moet doen." +

"Effect op klimaatverandering - Plasticvervuiling en klimaatverandering gaan hand in hand. Plastic wordt gemaakt van fossiele brandstoffen. Het verwerken van fossiele brandstoffen veroorzaakt uitstoot van broeikasgassen, is één van de grootste bijdragers aan de opwarming van de aarde." +

"Plasticvervuiling neemt toe - Doordat we steeds meer plastic gebruiken, stijgt ook de vraag naar producten gemaakt van aardolie. Zelfs als we proberen minder fossiele brandstoffen te gebruiken in, bijvoorbeeld auto's en huizen, zal het gebruik van plastic alleen maar toenemen, als we op deze manier doorgaan. Het Centrum voor Internationaal Milieurecht (CIEL) denkt dat tegen 2050 plastic 20% van al het oliegebruik zal zijn." +

"Plasticverbranding is ook een probleem - Het is in veel delen van de wereld gebruikelijk dat afval op open vuilnisbelten wordt verbrand, wat leidt tot ernstige luchtvervuiling. Het verbranden van plastic produceert giftige chemicaliën die schadelijk zijn voor, zowel het milieu, als de mensen die de vervuilde lucht inademen. Eén van de gevaarlijke stoffen die vrijkomen, is zwarte koolstof. Zwarte koolstof kan de aarde veel sneller opwarmen, wel tot 5000 keer sneller dan koolstofdioxide." +

"Afvalplastic veroorzaakt ook klimaatverandering - Veel van het plastic dat niet bij de recyclingfabriek terechtkomt, belandt in onze rivieren en oceanen. Dit is niet alleen gevaarlijk voor de dieren en planten wiens leefgebieden zijn veranderd in onderwater-afvalhopen, maar het vormt ook een bedreiging voor het klimaat. Plastic stoot broeikasgassen uit wanneer het langzaam afbreekt. Zonlicht en warmte zorgen ervoor dat het methaan en etheen vrijgeeft - en dat gebeurt steeds sneller naarmate het plastic in steeds kleinere stukjes uiteenvalt. Onderzoek laat ook zien dat microplastics het vermogen van zee-organismen om koolstofdioxide op te nemen en zuurstof vrij te geven, kunnen verstoren. Dit is belangrijk omdat de oceaan verantwoordelijk is voor ten minste de helft van de zuurstof op aarde, voornamelijk geproduceerd door plankton. Microplastics kunnen ervoor zorgen dat plankton minder goed groeien en minder voortplanten, waardoor er minder zuurstof uit de oceaan komt."

export default plasticConsequencesContent;