const plasticProblemContent = "Plastic, gemaakt van fossiele brandstoffen, bestaat pas iets meer dan honderd jaar, maar heeft ons leven volledig veranderd. Je ziet plastic al over je heen Plastic flessen voor water en frisdrank. Plastic boodschappentassen. Plastic verpakkingen voor voedsel, zoals bakjes, folie en zakken. Plastic tandenborstels en tandpastatubes. Plastic rietjes. Plastic speelgoed. Plastic wegwerp bestek." +
    
"Plastic heeft de dokters geholpen met spullen die levens redden, het heeft het mogelijk gemaakt om naar de ruimte te gaan, en het heeft auto's en vliegtuigen lichter gemaakt, waardoor ze minder benzine gebruiken en minder vieze lucht maken. Plastic wordt voor zoveel dingen gebruikt dat het moeilijk is om iets te bedenken waarin geen plastic wordt gebruikt. Het is heel handig, maar er is een probleem. Vaak gebruiken we plastic maar één keer en gooien het dan weg. Dit gebeurt vaak met plastic zakken en verpakkingen voor ons eten. Ook al gebruiken we ze maar heel kort, kan het honderden jaren duren voordat plastic volledig is afgebroken. En dat is niet goed voor het milieu." +

"Hoe plastic verplaatst - De meeste plastic rommel komt in de oceaan doordat mensen hun afval op straat of bij het water achterlaten. We kopen of gebruiken wegwerpproducten van plastic (voedselverpakkingen, plastic zakken, flessen, etc.) en we ruimen ze niet op de juiste manier op. Als we dat afval niet goed opruimen, kan het worden meegenomen door rivieren, wind en golven en uiteindelijk in de oceaan drijven. Het komt natuurlijk ook voor dat plastic direct in de oceaan wordt gegooid.Als plastic eenmaal in de zee belandt, blijft een groot deel ervan dichtbij de kust. Maar als het door de stroming van de oceaan wordt meegenomen, kan het over de hele wereld reizen." + 

"Microplastics Maar niet al het plasticafval in de oceaan komt door zwerfafval. Soms wordt plastic niet goed gemaakt en komen er microplastics in het water. Ook gooien sommige vissers plastic spullen in de oceaan, wat ook voor vervuiling zorgt. Microplastics zijn piepkleine stukjes plastic. Ze zijn zo klein dat ze door dieren in de zee kunnen worden opgegeten. Deze plastic deeltjes komen in het lichaam van de dieren terecht en kunnen problemen veroorzaken. Ze kunnen zelfs in ons voedsel terechtkomen als we deze dieren eten. Dat is slecht voor de gezondheid van onze planeet en alle levende wezens die erop wonen." + 

"Plasticvervuiling: Belangrijke Feiten - De productie is exponentieel toegenomen, van 2,3 miljoen ton in 1950 tot 400 miljoen ton in 2022. - De helft van alle plastic ooit geproduceerd is gemaakt in de laatste 15 jaar. - De productie wordt verwacht te verdubbelen tegen 2050. - De EPA (Environmental Protection Agency) heeft verklaard dat vrijwel 100% van al het plastic dat mensen ooit hebben gemaakt nog steeds bestaat. - Plastic afval vormt 80% van alle zeevervuiling en elk jaar belanden ongeveer 8 tot 10 miljoen ton plastic in de oceaan. - Onderzoek voorspelt dat plastic tegen 2050 waarschijnlijk meer zal wegen dan alle vissen in de zee. - Plastic doet er over het algemeen tussen de 500 en 1000 jaar over om af te breken. Zelfs dan wordt het microplastics, zonder volledig af te breken. - Momenteel zijn er ongeveer 50-75 biljoen stukjes plastic en microplastics in de oceaan. - Slechts 9% van het plasticafval in de wereld wordt gerecycled. De helft van al het plasticafval ter wereld belandt nog steeds gewoon op de vuilnisbelt. Een ander vijfde wordt niet goed behandeld, wat betekent dat het niet wordt gerecycled, verbrand of veilig opgeslagen in afgesloten stortplaatsen, waardoor het risico loopt om in rivieren, meren en de oceaan terecht te komen."

export default plasticProblemContent;